### ISSUE TITLE
Should we remove Form from react-bootstrap?

### ISSUE THREAD

**Issue by JonatanSalas** [redux-autoform/redux-autoform#57] opened 2016-07-29 20:40 UTC
@andrerpena In AutoFormInternal is still imported and used the Form component from react-bootstrap.

**Comment by danigomez** [comment] 2016-07-29 21:08
I think that we should remove it!, in case that is needed to define some root element we can add a method in the UIs factory :smile:

**Comment by JonatanSalas** [comment] 2016-07-29 21:26
Cool. I think that we could replace for a normal form not bootstrap, delete the dependency.

**Comment by andrerpena** [comment] 2016-07-30 15:58
The only reason why I use React-Bootstrap's Form instead of a regular form is because React-Bootstrap provides a form and the Bootstrap-UI _already_ has a dependency on React-Bootstrap. I mean.. Removing the dependency is not having any impact on the bundle size or anything.

But yes.. if that's what you want to do, you can replace and use the regular <form/>

**Comment by JonatanSalas** [comment] 2016-07-30 22:06
@andrerpena okey, I will do it so.. :smile:

**Comment by JonatanSalas** [comment] 2016-07-30 22:22
I think i should look more closer to the code because of this: 

``` jsx
render() {
        let { fieldLayout, ...rest } = this.props;

        return (
            <div className="meta-form">
                <Form onSubmit={handleSubmit} horizontal={fieldLayout == 'inline'}>
                    { groupComponent }
                    { React.createElement(buttonBar, { submitting: submitting }) }
                </Form>
            </div>
        )
    }
```

The trouble here is because of the horizontal prop that react-bootstrap have..

**Comment by danigomez** [comment] 2016-07-30 22:27
We can add the root element in an UIs factory method!, in case the method return a root component we set the children groupComponent and React.createElement to it, otherwise if that root component is not defined in the factory we use a normal form!

**Comment by JonatanSalas** [comment] 2016-07-30 22:30
@danigomez totally agree with it! I will ping you a little bit on monday to do this! :smile:

**Comment by andrerpena** [comment] 2016-07-31 03:20
Oh now I finally see the problem. I was thinking, what is the problem with using React-Bootstrap's form? The problem is that the form is inside `AutoFormInternal`, which shouldn't depend on Bootstrap.

Ok, now it makes absolute sense to replace it with a regular form and remove RAF's dependence on React-Bootstrap altogether.

**Comment by andrerpena** [comment] 2016-07-31 03:23
Also, about the field layout (stacked vs inline), don't bother with that. Let's make it Bootstrap only. Work with Material the way it's meant to be.

**Comment by andrerpena** [comment] 2016-07-31 03:25
Also, now I see why @danigomez is considering making the root element part of the Factory, that's because of the `horizontal` prop that is specific to Bootstrap. Actually.. the `horizontal` can be replaced by a css class.

Bottom line: **We can either make the root element part of the UI or we can just make the form CSS classes to be part of the UI**. Would just the CSS suffice?

**Comment by andrerpena** [comment] 2016-08-01 17:32
@JonatanSalas , because you are assigned to this task, here are some thoughts:

Today, what determines the UI type is the factory you pass in. The modes (edit, details and search) would change by passing different factories. So, if you want to operate in edit mode, you pass an edit factory. I'm thinking that it's better to replace these factories by a single "class", that would provide factories for edit, details and search. I mean.. instead of passing an edit factory. You pass 1 unified class that should be able to provide these factories. Why? Because now this unified class can also provide CSS classes for the form, or even a complete form control to use. This would ultimately solve this problem we have today with RAF depending on Bootstrap.

I could get this task, but I'm currently involved with the Redux-Form missing props release that I still couldn't test because it's not convenient.

**Comment by andrerpena** [comment] 2016-08-01 18:04
Also, I think the related "task" to this "question" would be to remove Bootstrap dependency from RAF altogether.

**Comment by JonatanSalas** [comment] 2016-08-01 18:19
@andrerpena well, with @danigomez we have think about having a class that resolves the factories itself.

**Comment by JonatanSalas** [comment] 2016-08-01 18:36
@andrerpena @danigomez after a time on thinking about this, I would prefer to keep the code as simple as possible. The horizontal property is related to react-boostrap and could be emulated easy by just using css or inline styles. So I will delete the bootstrap form import and use a normal form and I will emulate this prop by css.

**Comment by JonatanSalas** [comment] 2016-08-01 22:17
Since this is already solved, I will close it.

**Comment by andrerpena** [comment] 2016-08-01 22:22
Yes, I mean, the only thing left is to make the form bootstrap-free. But you can close it if you want. I think it makes sense to close this question and to open an issue which is actually making it bootstrap-free. Even though the reference has been removed, it's still using a class that is bootstrap-specific.

**Comment by JonatanSalas** [comment] 2016-08-01 22:26
@andrerpena but it doesn't make so much trouble, because it only will work when bootstrap-ui it's used. 
We have no direct dependency now on bootstrap, because if you just use material-ui then, it won't take the 'form-horizontal' className.

**Closed as completed** 2016-08-01 22:28 UTC
Labels: question

**Comment by andrerpena** [comment] 2016-08-01 22:31
Agreed!
